### ISSUE TITLE
Feedback badges are gray if the submission fails to an exception

### ISSUE THREAD

**Issue by Mankro** [apluslms/python-grader-utils#29]
If the student code raises an exception, the badges in the feedback HTML are gray and they don't have any context class like `badge-danger`. The PR #27 fixed the CSS so that the `badge-danger` is red, but now the contextual class is missing from the HTML.

**Comment by ihalaij1** [comment]
The error badges have always been gray to make it easily visible to the student when something is actually broken with their code. Failures have been red and successes green.

I'm not sure if it is a good idea from a user perspective to have both fails and errors shown in the same color.

I think the error badges should have their own contextual class. The default color of badge used to be gray.

**Comment by Mankro** [comment]
OK, the colour of errors can be changed. Maybe dark orange?
