### ISSUE TITLE
Feedback embeds badges in the title, but it messes up screen readers

### ISSUE THREAD

**Issue by Mankro** [apluslms/python-grader-utils#31]
The feedback uses `<h5>` heading that also contains the points badge and the success label. However, screen readers do not behave well when the heading contains multiple badges. It would be better if the heading contains only the result title and not the badges. This may require some changes in the CSS styles too.

https://github.com/apluslms/python-grader-utils/blob/4025fd929696fc28c3d4b4ecc8416acbd6efb59d/graderutils_format/templates/feedback.html#L43-L66

Screen readers may read only link text or other text too. When testing, pay attention when you are focusing only on the link `<a>` element and when you read the whole title. The problem is that the screen reader may read it like this: integers in the range 0 100, _heading level 5_, 0 slash 100 points _heading level 5_, success _heading level 5_. Repeating the heading announcement is frustrating.

In Ubuntu 20.04, you can use the built-in screen reader (Settings - Universal Access) or install the Orca screen reader.

**Comment by ihalaij1** [comment]
I remember testing with some browser extension screen reader when the points badges were first added, and it seemed to read it just fine. But I will look into those other screen readers and figure out some changes.
