### ISSUE TITLE
Update old example code and documentation

### ISSUE THREAD

**Issue by atilante** [apluslms/python-grader-utils#36]
It seems that the file [graderutils/test_config.yaml](https://github.com/apluslms/python-grader-utils/blob/master/graderutils/test_config.yaml) is the actual up-to-date documentation of the format of **test_config.yaml**, defined by the JSON Schema at [graderutils/schemas/test_config_v1_3.yaml](https://github.com/apluslms/python-grader-utils/tree/master/graderutils/schemas).

If so, the following documentation files should also be updated:

- [README.md](https://github.com/apluslms/python-grader-utils/blob/master/graderutils/README.md)
- [graderutils/README.md](https://github.com/apluslms/python-grader-utils/blob/master/graderutils/test_config.yaml)
- [examples/](https://github.com/apluslms/python-grader-utils/tree/master/examples)

This is quite important because of issue #35: newer Graderutils crashes if the config is malformed.

**Comment by ihalaij1** [comment]
Yes, I can update the readmes, they seem to be a bit outdated regarding validation tasks.
And as @Mankro said, the examples in this repository should be updated and moved to Aplus-manual.
